<?php
/**
 * @link      http://importantcoding.com
 * @copyright Copyright (c) 2019 Darryl Hardin
 */

namespace importantcoding\businesstobusiness\events;

use craft\commerce\elements\Order;
use craft\commerce\models\Discount;
use craft\commerce\models\OrderAdjustment;
use craft\events\CancelableEvent;

/**
 * Class IC DiscountAdjustmentsEvent
 *
 * @author    Darryl Hardin
 * @package   BusinessToBusiness
 * @since     1.0.0
 */
class DiscountAdjustmentsEvent extends CancelableEvent
{
    // Properties
    // =========================================================================

    /**
     * @var Order The order the discount generated the adjustments for. Do not mutate.
     */
    public $order;

    // /**
    //  * @var Discount The voucherValue that matched.
    //  */
    // public $discount;

    /**
     * @var OrderAdjustment[] The adjustments generated by the discount.
     */
    public $adjustments;
}